apiVersion: v1
kind: Service
metadata:
  name: restful-service-nodeport
spec:
  type: NodePort
  selector:
    app: restful-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080   
  
